name: Creative Creatures
favicon: null
layout_spectrum: 0.25181
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#000000'
    - '#383838'
    - '#9d9d9d'
    - '#656565'
  brandStrength: 0.602305113337934
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.8032363341189921
purpose: []
